# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# sed -i 's|SCKEY = ""|SCKEY = "${{ secrets.SCKEY }}"|' action.py
name: 网易云音乐

on:
  schedule:
    - cron: "0 0,16,20 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Script
        env:
          PHONE: ${{ secrets.PHONE }}
          PASSWORD: ${{ secrets.PASSWORD }}
          NOMD5_PASSWORD: ${{ secrets.NOMD5_PASSWORD }}
          PLAYLIST: ${{ secrets.PLAYLIST }}
          SCKEY: ${{ secrets.SCKEY }}
        run: |
        
          
          random_time=$(($RANDOM % 1))
          echo "等待 ${random_time} 分钟后开始签到"
          for((i=1;i<=${random_time};i++));  
          do
          echo "倒计时:剩余 $[${random_time}-$i] 分钟"
          sleep 1m
          done
          
          if [ ${NOMD5_PASSWORD} ];then PASSWORD=$(echo -n "${NOMD5_PASSWORD}"|md5sum|cut -d " " -f1); fi
          if [ ${PLAYLIST} ];then PLAYLIST_CMD="-l $PLAYLIST"; fi
          python3 action.py ${PHONE} ${PASSWORD} -s ${SCKEY} ${PLAYLIST_CMD}
